name: ci
on:
  push:
    branches:
      - main
      - develop
      - 'feat/**'
      - 'fix/**'
      - 'hotfix/**'
      - 'refactor/**'
      - 'chore/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    name: 리액트 프로젝트 빌드
    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v2
      
      - name: 노드 버전 체크
        run: node -v

      - name: 노드 모듈 캐싱
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      
      - name: 패키지 설치
        run: npm install
      
      - name: 패키지 빌드 
        run: npm run build
